### ISSUE TITLE
Improperly licensed derivative of GM_config

### ISSUE THREAD

**Issue by Martii** [gm-config/GM_config#1] opened 2017-11-24 09:41 UTC
See sizzlemctwizzle/GM_config#84

**Comment by sizzlemctwizzle** [comment] 2017-11-24 22:59
You and I both know you re-wrote [GM_config](https://github.com/sizzlemctwizzle/GM_config) by using the original source, past and present, as a reference. I am the primary author of the original. I developed it over the course of years with the help of others. I am not trying to discount the value of your work or that it is your work. But it is not your work alone. You have built on the work of others.

I created GM_config because there was nothing like it at the time (2009). Every script author who had a script that was complex enough to require graphical configuration threw together some custom haphazard code. It was always done by injecting strings of HTML into some element on the page. It was easier that building the elements, but it was never reusable or flexible. GM_config was designed to be easy to begin using, and as flexible as possible to allow for very advance use cases.

I designed the original external API, and the changes to it. I designed most of the internal logic and functionality, and the changes to it. Which is why you can't claim to have woken up one day and wrote this library from scratch. Because I didn't. GM_config evolved into what it is, what it does, and how it works. The logic and functionality comes from personal experience, feature requests, observation of users, and opinions/code from contributors. Your work has benifited from all of this. You might have typed every character yourself, but that doesn't make it an original work. But just because it isn't original doesn't mean it isn't good work. There is no shame in admitting that you did a radical re-implemention of GM_config. Your work is still your work and you deserve the credit, but so do all the others who've came before and made it possible to do your work.

So please stop fighting us and just join us already. Release your derivative under the LGPL v3+, and add yourself as an author in the copyright header. Perhaps your version can be merged upstream and become the basis for the future of GM_config. And then maybe someday someone won't publish a derivative of your work and claim that it is theirs and they can release it under any license they want. That is exactly what the LGPL protects against, while the MIT does not. You release your code so that others can distribute and make derivatives of their own under the condition that they do the same. The LGPL, unlike the GPL, also allows code released under any license to use your LGPL code during execution. The license does not require code using GM_config to be released under the LGPL.

**Closed** 2017-11-25 00:41 UTC
